name: Lint

on:
  pull_request:
    branches: [main,master]
  push:
    branches: [main,master]
  workflow_dispatch:

jobs:
  commit:
    uses: zdharma-continuum/.github/.github/workflows/commit-job.yml@main
  files:
    uses: zdharma-continuum/.github/.github/workflows/lint-job.yml@main
